<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'gatewayfactorytest' => '/unit/db/gatewayFactoryTests.php',
                'mongolibrarygatewaytest' => '/unit/db/mongoLibraryGatewayTests.php',
                'mongoprojectgatewaytest' => '/unit/db/mongoProjectGatewayTests.php',
                'orphanedsectionexceptiontests' => '/unit/plugins/project/exceptions/OrphanedSectionExceptionTests.php',
                'sessiontest' => '/unit/model/sessionTests.php',
                'usertest' => '/unit/model/usersTests.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd