<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'gatewayfactorytests' => '/unit/db/gatewayFactoryTests.php',
                'mongogatewaytests' => '/unit/db/mongoGatewayTests.php',
                'sessiontests' => '/unit/model/sessionTests.php',
                'userstests' => '/unit/model/usersTests.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd