<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'doxer\\controllers\\basecontroller' => '/controllers/BaseController.php',
                'doxer\\controllers\\homecontroller' => '/controllers/HomeController.php',
                'doxer\\controllers\\library\librarycontroller' => '/controllers/library/LibraryController.php',
                'doxer\\controllers\\project\projectcontroller' => '/controllers/project/ProjectController.php',
                'doxer\\controllers\\section\sectioncontroller' => '/controllers/section/SectionController.php',
                'doxer\\db\\gatewayfactory' => '/db/gatewayFactory.php',
                'doxer\\db\\iprojectsgateway' => '/db/iProjectsGateway.php',
                'doxer\\db\\mongoprojectsgateway' => '/db/mongoProjectsGateway.php',
                'doxer\\model\\library' => '/model/Library.php',
                'doxer\\model\\project' => '/model/Project.php',
                'doxer\\model\\section' => '/model/Section.php',
                'doxer\\model\\session' => '/model/Session.php',
                'doxer\\model\\user' => '/model/User.php',
                'marshall\\model\\nonpersistentbean' => '/model/NonPersistentBean.php'


            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd