<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'doxer\\db\\gatewayfactory' => '/db/gatewayFactory.php',
                'doxer\\db\\ilibrarygateway' => '/db/iLibraryGateway.php',
                'doxer\\db\\iprojectsgateway' => '/db/iProjectsGateway.php',
                'doxer\\db\\mongolibrarygateway' => '/db/mongoLibraryGateway.php',
                'doxer\\db\\mongoprojectsgateway' => '/db/mongoProjectsGateway.php',
                'doxer\\plugins\\home\\_plugin' => '/plugins/home/_plugin.php',
                'doxer\\plugins\\home\\homecontroller' => '/plugins/home/HomeController.php',
                'doxer\\plugins\\library\\_plugin' => '/plugins/library/_plugin.php',
                'doxer\\plugins\\library\\librarycontroller' => '/plugins/library/LibraryController.php',
                'doxer\\plugins\\library\\model\\library' => '/plugins/library/model/library.php',
                'doxer\\plugins\\project\\_plugin' => '/plugins/project/_plugin.php',
                'doxer\\plugins\\project\\exceptions\\orphanedsectionexception' => '/plugins/project/exceptions/OrphanedSectionException.php',
                'doxer\\plugins\\project\\model\\project' => '/plugins/project/model/project.php',
                'doxer\\plugins\\project\\model\\section' => '/plugins/project/model/section.php',
                'doxer\\plugins\\project\\projectcontroller' => '/plugins/project/ProjectController.php',
                'doxer\\plugins\\project\\sectioncontroller' => '/plugins/project/SectionController.php',
                'doxer\\plugins\\user\\model\\user' => '/plugins/user/model/user.php',
                'markdown_parser' => '/phplib/markdown.php',
                'markdownextra_parser' => '/phplib/markdown.php',
                'marshall\\core\\basecontroller' => '/core/BaseController.php',
                'marshall\\core\\baseplugin' => '/core/BasePlugin.php',
                'marshall\\core\\menu' => '/core/Menu.php',
                'marshall\\core\\menuitem' => '/core/MenuItem.php',
                'marshall\\core\\nonpersistentbean' => '/core/NonPersistentBean.php',
                'marshall\\core\\session' => '/core/session.php',
                'textile' => '/phplib/markdown.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd